name       : lynx
version    : 2.8.8.2
release    : 3
source     :
    - http://invisible-mirror.net/archives/lynx/tarballs/lynx2.8.8rel.2.tar.gz : 234c9dc77d4c4594ad6216d7df4d49eae3019a3880e602f39721b35b97fbc408
license    : GPL-2.0
summary    : Lynx is the text web browser
description: |
    Lynx is the oldest text web browser still actively developed.
builddeps  :
    - pkgconfig(ncursesw)
    - pkgconfig(openssl)
setup      : |
    %configure --prefix=/usr --enable-ipv6 --enable-nls --with-ssl=/usr
build      : |
    %make
install    : |
    %make_install
